#!/bin/bash -e
set -e # crash on error
DIR=".give_ssh/"
EX="Ex: give_ssh cs6741 a1 \"a1/a1 sol.pdf\""

function main {
    class=$1
    assignment=$2
    files=("${@:3}")
    l_files=("${files[@]/*\//}")
    l_files=("${l_files[@]/ /\\ }")
    ssh -t $cse "rm -rf $DIR && mkdir $DIR"
    scp "${files[@]}" "$cse:$DIR"
    echo "give $class $assignment ${l_files[@]}"
    ssh -t $cse "cd $DIR && give $class $assignment ${l_files[@]}"
}

function no_cse_env {
    echo "\$cse variable needs to be set to your ssh address."
    echo "add \"export cse=zXXXXXXX@cse.unsw.edu.au\" to your ~/.bashrc"
}

if [ -z "$cse" ]; then
    no_cse_env
    exit 1
elif [[ $# < 3 ]]; then
    echo $EX
    exit 1
fi

main "$@"
