#!/bin/bash -e
set -e # crash on error
DIR=".give_ssh/"
EX="Ex: give_ssh cs6741 a1 \"a1/a1 sol.pdf\""
LOC_DIR="/tmp/$DIR"

function main {
    class=$1
    assignment=$2
    files=("${@:3}")
    l_files=("${files[@]/*\//}")
    l_files=("${l_files[@]/ /\\ }")
    copy_to_local_dir "${files[@]}"
    scp -r "$LOC_DIR" $cse:
    echo "give $class $assignment ${l_files[@]}"
    ssh -t $cse "cd $DIR && give $class $assignment ${l_files[@]}"
}

function copy_to_local_dir {
    files=("$@")
    if [[ ${#DIR} > 1 ]] && [[ "${DIR: -1}" == "/" ]]; then
        rm -rf "$LOC_DIR"; mkdir "$LOC_DIR"
        cp "${files[@]}" "$LOC_DIR"
    else
        echo "Check \$DIR"
        exit 1
    fi
}

function no_cse_env {
    echo "\$cse variable needs to be set to your ssh address."
    echo "add \"export cse=zXXXXXXX@cse.unsw.edu.au\" to your ~/.bashrc"
}

if [ -z "$cse" ]; then
    no_cse_env
    exit 1
elif [[ $# < 3 ]]; then
    echo $EX
    exit 1
fi

main "$@"
